version: "3.9"

services: 
  app:
    build: .
    entrypoint: ["sh", "-c", "dockerize -wait tcp://mongo:27017 -timeout 20s -wait tcp://rabbitmq:5672 -timeout 20s pnpm install && pnpm build && pnpm run start"]
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "zhavia_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: qwe123
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: "zhavia_mongdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
