version: "3.9"

services: 
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "zhavia_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: qwe123

  mongo:
    image: mongo
    container_name: "zhavia_mongdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    ports:
      - "27017:27017"
